name: CI
on: [push]
jobs:
  simple:
    runs-on: ubuntu-latest
    name: Test a simple blueprint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cloudify CLI
        uses: cloudify-cosmo/cli-action@v1.1
        with:
          # Command to run
          command: deployments create -b Kubernetes-GCP-GKE -i environments/dev-gcp.yaml github-action-deployment
          set-output: true
env:
  CLOUDIFY_HOST: ${{ secrets.CLOUDIFY_HOST }}
  CLOUDIFY_USERNAME: ${{ secrets.CLOUDIFY_USERNAME }}
  CLOUDIFY_PASSWORD: ${{ secrets.CLOUDIFY_PASSWORD }}
  CLOUDIFY_SSL: ${{ secrets.CLOUDIFY_SSL }}
  CLOUDIFY_SSL_TRUST_ALL: ${{ secrets.CLOUDIFY_SSL_TRUST_ALL }}
