# This is a basic workflow to help you get started with Actions

name: CI
on: [push]
jobs:
  simple:
    runs-on: ubuntu-latest
    name: Test a simple blueprint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create environment
        uses: cloudify-cosmo/install-or-update@v1.1
        with:
          environment-name: "github-action-environment"
          blueprint-id: "Kubernetes-GCP-GKE"
          inputs-file: "environments/dev-gcp.yaml"
          delete-old-blueprint: "true"
          outputs-file: env-data.json




